export const testPolls = [
  {
    polling_source: 'YouGov/Economist',
    date: '2019-06-18T07:00:00.000Z',
    sample_size: '576',
    margin_of_error: '-',
    state: '',
    joe_biden: 26,
    cory_booker: 2,
    pete_buttigieg: 9,
    kamala_harris: 7,
    beto_o_rourke: 4,
    bernie_sanders: 13,
    elizabeth_warren: 14,
    amy_klobuchar: '-',
    deval_patrick: '-',
    andrew_yang: '-',
    billde_blasio: '-',
    kirsten_gillibrand: '-',
    julian_castro: '-',
    michael_bloomberg: '-',
    hillary_clinton: '-',
    michelle_obama: '-',
    andrew_cuomo: '-',
    oprah_winfrey: '-'
  },
  {
    polling_source: 'Change Research',
    date: '2019-06-17T07:00:00.000Z',
    sample_size: '1130',
    margin_of_error: '2.9',
    state: 'Florida',
    joe_biden: 33,
    cory_booker: 2,
    pete_buttigieg: 15,
    kamala_harris: 7,
    beto_o_rourke: 3,
    bernie_sanders: 20,
    elizabeth_warren: 15,
    amy_klobuchar: '-',
    deval_patrick: '-',
    andrew_yang: '-',
    billde_blasio: '-',
    kirsten_gillibrand: '-',
    julian_castro: '-',
    michael_bloomberg: '-',
    hillary_clinton: '-',
    michelle_obama: '-',
    andrew_cuomo: '-',
    oprah_winfrey: '-'
  },
  {
    polling_source: 'Quinnipiac University',
    date: '2019-06-17T07:00:00.000Z',
    sample_size: '417',
    margin_of_error: '5.8',
    state: 'Florida',
    joe_biden: 41,
    cory_booker: 1,
    pete_buttigieg: 8,
    kamala_harris: 6,
    beto_o_rourke: 1,
    bernie_sanders: 14,
    elizabeth_warren: 12,
    amy_klobuchar: '-',
    deval_patrick: '-',
    andrew_yang: '-',
    billde_blasio: '-',
    kirsten_gillibrand: '-',
    julian_castro: '-',
    michael_bloomberg: '-',
    hillary_clinton: '-',
    michelle_obama: '-',
    andrew_cuomo: '-',
    oprah_winfrey: '-'
  },
  {
    polling_source: 'Monmouth University',
    date: '2019-06-17T07:00:00.000Z',
    sample_size: '306',
    margin_of_error: '5.6',
    state: '',
    joe_biden: 32,
    cory_booker: 2,
    pete_buttigieg: 5,
    kamala_harris: 8,
    beto_o_rourke: 3,
    bernie_sanders: 14,
    elizabeth_warren: 15,
    amy_klobuchar: '-',
    deval_patrick: '-',
    andrew_yang: '-',
    billde_blasio: '-',
    kirsten_gillibrand: '-',
    julian_castro: '-',
    michael_bloomberg: '-',
    hillary_clinton: '-',
    michelle_obama: '-',
    andrew_cuomo: '-',
    oprah_winfrey: '-'
  },
  {
    polling_source: 'Morning Consult',
    date: '2019-06-16T07:00:00.000Z',
    sample_size: '17226',
    margin_of_error: '1',
    state: '',
    joe_biden: 50,
    cory_booker: '-',
    pete_buttigieg: '-',
    kamala_harris: '-',
    beto_o_rourke: '-',
    bernie_sanders: 34,
    elizabeth_warren: '-',
    amy_klobuchar: '-',
    deval_patrick: '-',
    andrew_yang: '-',
    billde_blasio: '-',
    kirsten_gillibrand: '-',
    julian_castro: '-',
    michael_bloomberg: '-',
    hillary_clinton: '-',
    michelle_obama: '-',
    andrew_cuomo: '-',
    oprah_winfrey: '-'
  }
];
